# Generated by Django 3.1.2 on 2020-10-28 07:22

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tutorial_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('tutorial_content', models.TextField()),
                ('published', models.BooleanField()),
                ('created_on', models.DateField()),
                ('postded_on', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
